# Generated by Django 3.1.1 on 2021-01-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('appetizer', 'Appetizer'), ('main food', 'Mainfood'), ('specials', 'Specials'), ('dessert', 'Dessert')], max_length=100),
        ),
    ]
