# Generated by Django 3.1.1 on 2021-01-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
